---

- name: install sysstat
  yum:
    name: sysstat

- name: configure sysstat
  template:
    src: 'sysstat-conf-{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.j2'
    dest: '/etc/sysconfig/sysstat'
    owner: root
    group: root
    mode: 0644

- name: configure sysstat cron
  template:
    src: 'sysstat-cron.j2'
    dest: '/etc/cron.d/sysstat'
    owner: root
    group: root
    mode: 0600

- name: set sysstat service status
  service:
    name: sysstat
    enabled: '{{ sysstat_sar_service }}'
  tags:
    - service

...
